# Generated by Django 6.0.4 on 2026-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('FULL_DAY', 'Full Day')], default='HOURLY', max_length=20),
        ),
        migrations.AddField(
            model_name='loungeroom',
            name='price_full_day',
            field=models.DecimalField(decimal_places=2, default=30000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
