# Generated by Django 6.0.4 on 2026-05-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_customer_email_booking_customer_nin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('AVAILABLE', 'Room available'), ('BUSY', 'Room busy'), ('FREE_SOON', 'The Room is free in the next Hour'), ('UNAVAILABLE', 'Room not available'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
