# Generated by Django 6.0.4 on 2026-05-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_phone_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Name'),
        ),
    ]
